[package]
name = "lumine"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
toml = "0.9.11"
xdg = "3.0.0"
serde = { version = "1.0.228", features = ["derive"] }
regex = "1.12.2"
chrono = "0.4.42"
reqwest = { version = "0.13.1", features = ["blocking", "multipart"] }
serde_json = "1.0.149"
thiserror = "2.0.17"

[lints.clippy]
needless_return = "allow"
upper_case_acronyms = "allow"
